object Versions {
    const val kotlinVersion = "1.4.30"
    const val hiltAndroidVersion = "2.31-alpha"
    const val hiltVersion = "1.0.0-alpha03"
    const val gradlePluginVersion = "7.0.0-alpha09"
    const val coreKtxVersion = "1.3.2"
    const val appCompatVersion = "1.2.0"
    const val materialVersion = "1.2.1"
    const val composeVersion = "1.0.0-beta01"
    const val navComposeVersion = "1.0.0-alpha08"
    const val activityComposeVersion = "1.3.0-alpha03"
    const val lifecycleVersion = "2.2.0"
    const val glideVersion = "4.11.0"
    const val roomVersion = "2.2.6"
    const val retrofitVersion = "2.9.0"
    const val serializationConverterVersion = "0.8.0"
    const val datastoreVersion = "1.0.0-alpha06"
    const val accompanistVersion = "0.6.0"
    const val junitVersion = "4.13.1"
    const val junitExtVersion = "1.1.2"
    const val espressoVersion = "3.3.0"
}